// <auto-generated />
namespace SleepyStore.WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Stf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Stf));
        
        string IMigrationMetadata.Id
        {
            get { return "202011171823389_Stf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
